remote_theme: pages-themes/cayman@v0.2.0
title: "Marcos Antonio Espinoza Mina, PhD"
description: "Doctor en Administración | Especialista en Analítica de Datos e IA | Perito Informático"
show_downloads: false
google_analytics:
