remote_theme: pages-themes/cayman@v0.2.0
title: "Marcos Antonio Espinoza Mina, PhD"
description: "Doctor en Administración | Especialista en Analítica de Datos e IA | Docente Universitario"

# Desactivar botones predeterminados del tema
show_downloads: false
github:
  is_project_page: false
