remote_theme: pages-themes/minimal@v0.2.0
title: "Dr. Marcos Antonio Espinoza Mina"
description: "Doctor en Administración | Magíster en Estadística, Sistemas y Negocios | Docente Universitario"
logo: "/mespinoza.jpg"

show_downloads: false
google_analytics: 
github:
  is_project_page: false
